import type { KellyWorkbenchData } from "./types";

export const createKellyWorkbenchDemoData = (): KellyWorkbenchData => ({
  title: "Kelly 实验台",
  subtitle: "把天气证据、模型表现和盘口价格压到同一工作面，只先定义 UI 载体，不预设最终公式。",
  locationId: "shanghai_pvg",
  locationOptions: [
    { id: "shanghai_pvg", label: "Shanghai Pudong", labelZh: "上海浦东", shortLabel: "PVG", timezone: "Asia/Shanghai", timezoneGroup: "asia" },
    { id: "wuhan_wuh", label: "Wuhan Tianhe", labelZh: "武汉天河", shortLabel: "WUH", timezone: "Asia/Shanghai", timezoneGroup: "asia" },
    { id: "istanbul_ist", label: "Istanbul Airport", labelZh: "伊斯坦布尔", shortLabel: "IST", timezone: "Europe/Istanbul", timezoneGroup: "europe" },
    { id: "munich_muc", label: "Munich Airport", labelZh: "慕尼黑", shortLabel: "MUC", timezone: "Europe/Berlin", timezoneGroup: "europe" },
    { id: "toronto_yyz", label: "Toronto Pearson", labelZh: "多伦多", shortLabel: "YYZ", timezone: "America/Toronto", timezoneGroup: "americas" },
    { id: "miami_mia", label: "Miami International", labelZh: "迈阿密", shortLabel: "MIA", timezone: "America/New_York", timezoneGroup: "americas" },
  ],
  targetDate: "2026-04-06",
  dateOptions: ["2026-04-06", "2026-04-07", "2026-04-08"],
  dateChips: [
    { value: "2026-04-06", label: "今天 · 04-06", shortLabel: "04-06", selected: true },
    { value: "2026-04-07", label: "明天 · 04-07", shortLabel: "04-07" },
    { value: "2026-04-08", label: "后天 · 04-08", shortLabel: "04-08" },
  ],
  bankrollInput: "2500",
  minEdgeInput: "2.5",
  actualTemperatureInput: "25.8",
  riskMode: "balanced",
  riskModeOptions: [
    { value: "conservative", label: "保守" },
    { value: "balanced", label: "平衡" },
    { value: "aggressive", label: "进取" },
  ],
  marketUrl: "https://polymarket.com/",
  syncMetrics: [
    { id: "weather", label: "天气证据", value: "meteoblue 1h + multi-model", detail: "当前地点真实链路", tone: "accent" },
    { id: "market", label: "盘口快照", value: "Gamma + top-of-book", detail: "只读行情层", tone: "warning" },
    { id: "freshness", label: "刷新状态", value: "2026-04-06 11:42", detail: "示例数据 / UI 骨架", tone: "success" },
  ],
  summaryMetrics: [
    { id: "consensus", label: "主观峰值", value: "27.6-28.2°C", detail: "Top ensemble band", tone: "accent" },
    { id: "bias", label: "当前偏差", value: "+0.4°C", detail: "Nowcast weighted bias", tone: "success" },
    { id: "best", label: "最佳观察窗", value: "14:00-15:00", detail: "Peak cluster", tone: "warning" },
    { id: "edge", label: "可交易 edge", value: "3.8%-7.1%", detail: "After min edge filter", tone: "accent" },
  ],
  opportunities: [
    {
      id: "market-28-yes",
      marketId: "market-28",
      tier: "primary",
      title: "主仓建议",
      marketLabel: "28°C 及以上",
      side: "yes",
      thesis: "当前实况略高于主流模型均值，峰值窗口集中，盘口 still below our fair yes.",
      confidenceLabel: "高",
      edgePct: 6.2,
      fairPricePct: 58.4,
      marketPricePct: 52.2,
      kellyPct: 7.4,
      suggestedStakeUsd: 186,
      reasons: ["当前时点偏差向上", "高温峰值集中在 14-15 时", "前排模型分歧可控"],
      tags: ["主仓", "天气证据强", "盘口仍有空间"],
    },
    {
      id: "market-29-no",
      marketId: "market-29",
      tier: "primary",
      title: "副仓建议",
      marketLabel: "29°C 及以上",
      side: "no",
      thesis: "29°C 需要尾部扩张才能成立，当前分布右尾还不够厚，No side 更合理。",
      confidenceLabel: "中高",
      edgePct: 4.1,
      fairPricePct: 61.3,
      marketPricePct: 57.2,
      kellyPct: 4.8,
      suggestedStakeUsd: 121,
      reasons: ["尾部样本稀薄", "高位模型只占少数", "盘口溢价略高"],
      tags: ["副仓", "反尾部", "Kelly 较低"],
    },
    {
      id: "market-27-yes",
      marketId: "market-27",
      tier: "watch",
      title: "观察仓",
      marketLabel: "27°C 及以上",
      side: "watch",
      thesis: "胜率高但盘口已经压缩，适合作为对照，不适合继续做大。",
      confidenceLabel: "中",
      edgePct: 1.1,
      fairPricePct: 71.2,
      marketPricePct: 70.1,
      kellyPct: 0.9,
      suggestedStakeUsd: 22,
      reasons: ["盘口接近公平价", "更多适合做校验", "不满足主仓 edge"],
      tags: ["观察", "接近平价"],
    },
  ],
  probability: {
    title: "概率主视觉",
    subtitle: "以主观温度分布为中心，叠加盘口阈值与可交易区。",
    summary: "当前设计只做 UI 容器。后续可把你的 edge engine 输出为单峰或多峰分布，直接映射到市场区间。",
    samples: [
      { temperatureC: 24, probabilityPct: 2.4 },
      { temperatureC: 25, probabilityPct: 6.8 },
      { temperatureC: 26, probabilityPct: 12.7 },
      { temperatureC: 27, probabilityPct: 18.1 },
      { temperatureC: 28, probabilityPct: 22.8 },
      { temperatureC: 29, probabilityPct: 18.6 },
      { temperatureC: 30, probabilityPct: 11.2 },
      { temperatureC: 31, probabilityPct: 5.4 },
      { temperatureC: 32, probabilityPct: 2.0 },
    ],
    thresholds: [
      { id: "curve-27", label: "27°C", temperatureC: 27, detail: "盘口平价附近", marketId: "market-27", tone: "neutral" },
      { id: "curve-28", label: "28°C", temperatureC: 28, detail: "当前主仓标的", marketId: "market-28", tone: "accent" },
      { id: "curve-29", label: "29°C", temperatureC: 29, detail: "副仓 / 尾部", marketId: "market-29", tone: "warning" },
    ],
    confidenceBands: [
      { id: "band-core", fromC: 27.2, toC: 28.6, label: "核心概率带", tone: "accent" },
      { id: "band-tail", fromC: 28.6, toC: 29.4, label: "右尾观察带", tone: "warning" },
    ],
    notes: [
      "支持把 current bias、top model weights、peak clustering 映射成分布曲线。",
      "支持后续叠加 Polymarket 阈值、盘口中位价、你的主观 fair price。",
      "支持把实际成交密集区或盘口深度单独挂成次要图层。",
    ],
  },
  markets: [
    {
      id: "market-27",
      label: "27°C 及以上",
      rangeLabel: ">= 27°C",
      yesPricePct: 70.1,
      noPricePct: 31.4,
      fairYesPct: 71.2,
      fairNoPct: 28.8,
      yesEdgePct: 1.1,
      noEdgePct: -2.6,
      yesKellyPct: 0.9,
      noKellyPct: 0,
      suggestedStakeUsd: 22,
      recommendation: "观察",
      status: "tradable",
      detail: "盘口接近平价，更多用于校验。",
    },
    {
      id: "market-28",
      label: "28°C 及以上",
      rangeLabel: ">= 28°C",
      yesPricePct: 52.2,
      noPricePct: 48.6,
      fairYesPct: 58.4,
      fairNoPct: 41.6,
      yesEdgePct: 6.2,
      noEdgePct: -7.0,
      yesKellyPct: 7.4,
      noKellyPct: 0,
      suggestedStakeUsd: 186,
      recommendation: "主仓",
      status: "tradable",
      detail: "当前最高性价比区间。",
    },
    {
      id: "market-29",
      label: "29°C 及以上",
      rangeLabel: ">= 29°C",
      yesPricePct: 42.8,
      noPricePct: 57.2,
      fairYesPct: 38.7,
      fairNoPct: 61.3,
      yesEdgePct: -4.1,
      noEdgePct: 4.1,
      yesKellyPct: 0,
      noKellyPct: 4.8,
      suggestedStakeUsd: 121,
      recommendation: "副仓",
      status: "tradable",
      detail: "右尾需要额外催化才成立。",
    },
    {
      id: "market-30",
      label: "30°C 及以上",
      rangeLabel: ">= 30°C",
      yesPricePct: 19.6,
      noPricePct: 80.9,
      fairYesPct: 16.4,
      fairNoPct: 83.6,
      yesEdgePct: -3.2,
      noEdgePct: 2.7,
      yesKellyPct: 0,
      noKellyPct: 1.7,
      suggestedStakeUsd: 43,
      recommendation: "轻仓观察",
      status: "thin",
      detail: "盘口流动性较薄。",
    },
  ],
  unresolvedMarkets: [],
  evidenceSections: [
    {
      id: "weather-evidence",
      title: "天气证据",
      description: "优先展示真实来源、当前偏差与峰值聚类。",
      items: [
        { id: "obs", label: "当前参考温度", value: "25.8°C", detail: "来自当前小时参考值", tone: "success", sourceLabel: "dashboard.hourly", sourceUrl: "#" },
        { id: "bias", label: "加权 nowcast 偏差", value: "+0.4°C", detail: "Top 模型偏差加权", tone: "accent", sourceLabel: "insight", sourceUrl: "#" },
        { id: "peak", label: "峰值聚类", value: "14:00-15:00", detail: "峰值时段集中度 68%", tone: "warning", sourceLabel: "distribution + insight", sourceUrl: "#" },
      ],
    },
    {
      id: "market-evidence",
      title: "盘口证据",
      description: "展示 fair / market 对比和可执行性。",
      items: [
        { id: "book", label: "盘口层", value: "Top-of-book", detail: "读取最优 bid/ask 或中位价", tone: "accent", sourceLabel: "Polymarket", sourceUrl: "https://polymarket.com/" },
        { id: "spread", label: "价差状态", value: "窄", detail: "主仓标的价差可接受", tone: "success" },
        { id: "filter", label: "最小 edge 过滤", value: "2.5%", detail: "低于门槛不建议下单", tone: "warning" },
      ],
    },
    {
      id: "methodology",
      title: "公式占位",
      description: "这里预留你后续确定的 edge engine 解释层。",
      items: [
        { id: "engine", label: "主观概率输入", value: "模型能力加权", detail: "当前温度偏差 + 峰值分布 + 模型可靠度" },
        { id: "kelly", label: "头寸分配", value: "Kelly * risk mode", detail: "输出主仓 / 副仓 / 观察仓" },
      ],
    },
  ],
  methodologyNotes: [
    "UI 已预留天气证据、盘口证据和公式说明三层，不把 cadence 伪装成实时更新时间。",
    "机会面板、概率曲线、市场表都按同一市场 id 选中高亮，便于主线程后续接线。",
    "表格和 inspector 只依赖规范化 props，不依赖具体后端字段命名。",
  ],
  frameAnalysisGroups: [
    {
      id: "market-28-frames",
      title: "逐帧分析",
      description: "按刷新批次记录盘口与主观 fair 的偏移。",
      rows: [
        {
          id: "frame-1",
          label: "开盘后",
          timestampLabel: "10:10",
          marketLabel: "28°C 及以上",
          yesPricePct: 49.8,
          noPricePct: 50.2,
          fairYesPct: 55.6,
          fairNoPct: 44.4,
          marketPricePct: 49.8,
          fairPricePct: 55.6,
          yesEdgePct: 5.8,
          noEdgePct: -6.4,
          spreadPct: 2.4,
          weatherSignal: "当前偏差开始转正，峰值窗口稳定。",
          note: "第一轮可建仓。",
        },
        {
          id: "frame-2",
          label: "模型刷新后",
          timestampLabel: "11:00",
          marketLabel: "28°C 及以上",
          yesPricePct: 52.2,
          noPricePct: 47.8,
          fairYesPct: 58.4,
          fairNoPct: 41.6,
          marketPricePct: 52.2,
          fairPricePct: 58.4,
          yesEdgePct: 6.2,
          noEdgePct: -7.0,
          spreadPct: 2.0,
          weatherSignal: "高温带抬升，右尾没有同步扩张。",
          note: "主仓维持。",
        },
        {
          id: "frame-3",
          label: "盘口跟涨后",
          timestampLabel: "11:35",
          marketLabel: "28°C 及以上",
          yesPricePct: 56.6,
          noPricePct: 43.4,
          fairYesPct: 58.1,
          fairNoPct: 41.9,
          marketPricePct: 56.6,
          fairPricePct: 58.1,
          yesEdgePct: 1.5,
          noEdgePct: -2.1,
          spreadPct: 3.6,
          weatherSignal: "天气证据没继续强化，edge 被吃掉。",
          note: "仓位不宜再加。",
        },
      ],
    },
  ],
});
