export interface ModelCatalogEntry {
  code: string;
  aliases: string[];
  displayName: string;
  fullName: string;
  agency: string;
  domainType: "全球" | "区域";
  coverage: string;
  resolutionLabel: string;
  updateCadence: string;
  officialUpdateCadence: string;
  forecastHorizon: string;
  strengthsZh: string[];
  limitsZh: string[];
  officialSourceUrl: string;
  verifiedAt: string;
  officialVerifiedAt: string;
  sourceLevel: "official" | "provider";
  notes: string;
}

const verifiedAt = "2026-04-04";

const entries: ModelCatalogEntry[] = [
  {
    code: "AIFS025",
    aliases: ["AIFS-25"],
    displayName: "AIFS 0.25°",
    fullName: "ECMWF Artificial Intelligence Forecasting System",
    agency: "ECMWF",
    domainType: "全球",
    coverage: "全球中期趋势",
    resolutionLabel: "约 0.25°",
    updateCadence: "00/06/12/18 UTC，4 次/日",
    officialUpdateCadence: "00/06/12/18 UTC，4 次/日",
    forecastHorizon: "至 15 天",
    strengthsZh: ["适合快速读取大尺度温度趋势。", "适合与传统动力模式做交叉对照。"],
    limitsZh: ["不应单独承担局地对流判断。", "复杂地形与城市热岛仍需区域模式补充。"],
    officialSourceUrl: "https://www.ecmwf.int/en/forecasts/dataset/aifs-machine-learning-data",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "更适合看趋势和偏向，不等于当前时刻一定最准。",
  },
  {
    code: "IFS025",
    aliases: ["IFS-20"],
    displayName: "IFS 0.25°",
    fullName: "ECMWF Integrated Forecasting System",
    agency: "ECMWF",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "0.25° 开放数据子集",
    updateCadence: "00/12 UTC 主运行，06/18 UTC 补充产品",
    officialUpdateCadence: "00/12 UTC 主运行，06/18 UTC 补充产品",
    forecastHorizon: "至 15 天",
    strengthsZh: ["中期温度趋势通常可作为基准线。", "适合观察模型群的中心位置。"],
    limitsZh: ["站点级细节不能直接等同实况。", "午后对流和城市热岛仍需谨慎。"],
    officialSourceUrl: "https://www.ecmwf.int/en/forecasts/documentation-and-support/medium-range-forecasts",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "更适合看整体趋势，而不是把单个小时当成绝对真值。",
  },
  {
    code: "IFSHRES",
    aliases: ["IFS-HRES"],
    displayName: "IFS HRES",
    fullName: "ECMWF High Resolution Forecast",
    agency: "ECMWF",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "约 9 km",
    updateCadence: "00/12 UTC 主运行，06/18 UTC 补充产品",
    officialUpdateCadence: "00/12 UTC 主运行，06/18 UTC 补充产品",
    forecastHorizon: "至 10 天",
    strengthsZh: ["高分辨率下温度梯度更清晰。", "常作为全球确定性主力参考。"],
    limitsZh: ["仍不是站点级真值。", "沿海边界和局地降水仍要结合区域模式。"],
    officialSourceUrl: "https://www.ecmwf.int/en/forecasts/documentation-and-support/medium-range-forecasts",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "适合做主力确定性判断，但最好和区域模式交叉验证。",
  },
  {
    code: "ICON",
    aliases: ["ICON-12"],
    displayName: "ICON",
    fullName: "DWD ICON Global Model",
    agency: "DWD",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "约 13 km",
    updateCadence: "00/06/12/18 UTC，4 次/日",
    officialUpdateCadence: "00/06/12/18 UTC，4 次/日",
    forecastHorizon: "5 至 7.5 天",
    strengthsZh: ["温度场和云量结构通常较均衡。", "锋面与雨带位置有较强参考价值。"],
    limitsZh: ["复杂地形下仍会出现局地偏差。", "极端局地降雨不能只看单一场次。"],
    officialSourceUrl: "https://www.dwd.de/EN/ourservices/nwp_forecast_data/nwp_forecast_data.html",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "适合和 ECMWF、GFS 一起看大尺度分歧位置。",
  },
  {
    code: "GFS05",
    aliases: ["GFS-40"],
    displayName: "GFS 0.5°",
    fullName: "NOAA Global Forecast System",
    agency: "NOAA / NCEP",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "页面常见 0.5° 展示口径",
    updateCadence: "00/06/12/18 UTC，4 次/日",
    officialUpdateCadence: "00/06/12/18 UTC，4 次/日",
    forecastHorizon: "至 16 天",
    strengthsZh: ["更新频率高，适合观察场次变化。", "中短期趋势和峰值时段对比价值高。"],
    limitsZh: ["局地高温与对流细节波动可能较大。", "页面显示分辨率低于官方原始格点。"],
    officialSourceUrl: "https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/gfs.php",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "适合看最新场次方向变化，不宜只凭单场下结论。",
  },
  {
    code: "GEM15",
    aliases: ["GEM-15"],
    displayName: "GEM 15 km",
    fullName: "ECCC GDPS (GEM)",
    agency: "Environment and Climate Change Canada",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "约 15 km",
    updateCadence: "00/12 UTC，2 次/日",
    officialUpdateCadence: "00/12 UTC，2 次/日",
    forecastHorizon: "至 240 小时",
    strengthsZh: ["适合做跨机构交叉校验。", "对整体温度离散范围有参考意义。"],
    limitsZh: ["场次数量少于每日 4 次体系。", "城市尺度判断仍需更细模式辅助。"],
    officialSourceUrl: "https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps-datamart_en/",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "更适合作为跨机构参考，不是首页唯一判断来源。",
  },
  {
    code: "MSM",
    aliases: ["MSM-5"],
    displayName: "MSM",
    fullName: "JMA Meso-Scale Model",
    agency: "JMA",
    domainType: "区域",
    coverage: "日本及周边区域",
    resolutionLabel: "约 5 km",
    updateCadence: "多数每 3 小时一次",
    officialUpdateCadence: "多数每 3 小时一次",
    forecastHorizon: "39 至 78 小时",
    strengthsZh: ["区域精细度高，短时细节更敏感。", "近地层温度与局地变化更有参考价值。"],
    limitsZh: ["覆盖范围有限。", "超出主要覆盖区后不应与全球模式直接类比。"],
    officialSourceUrl: "https://www.jma.go.jp/jma/jma-eng/jma-center/nwp/outline2026-nwp/index.htm",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "使用前应先确认地点是否处在有效覆盖范围附近。",
  },
  {
    code: "UMGLOBAL10",
    aliases: ["UKMO-10"],
    displayName: "UM Global 10 km",
    fullName: "Met Office Unified Model Global Deterministic",
    agency: "UK Met Office",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "约 10 km",
    updateCadence: "每 6 小时更新",
    officialUpdateCadence: "每 6 小时更新",
    forecastHorizon: "至 168 小时",
    strengthsZh: ["适合和 IFS HRES、ICON 做高分辨率对照。", "温度峰值时段和云量演变有比较价值。"],
    limitsZh: ["页面展示仍是 provider 聚合结果。", "海陆风和午后对流仍需交叉验证。"],
    officialSourceUrl: "https://datahub.metoffice.gov.uk/docs/f/category/atmospheric/overview",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "适合在主流全球模式之间做时段分歧比较。",
  },
  {
    code: "MFGLOBAL",
    aliases: ["ARPEGE-25"],
    displayName: "Meteo-France Global",
    fullName: "Meteo-France ARPEGE Global",
    agency: "Meteo-France",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "欧洲附近约 5 km，远端约 24 km",
    updateCadence: "00/06/12/18 UTC，约每 6 小时",
    officialUpdateCadence: "00/06/12/18 UTC，约每 6 小时",
    forecastHorizon: "约 4 天",
    strengthsZh: ["提供法国体系的独立视角。", "适合观察峰值是否与主流模型一致。"],
    limitsZh: ["provider 页面未展开全部技术细节。", "站点表现仍需结合实时分布判断。"],
    officialSourceUrl: "https://meteofrance.com/modeles-prevision-meteo",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "当前页面使用 provider 命名，细节解释优先参考官方模型体系说明。",
  },
  {
    code: "NEMSGLOBAL",
    aliases: ["NEMS-30"],
    displayName: "NEMS Global",
    fullName: "meteoblue NEMS Global",
    agency: "meteoblue",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "约 30 km",
    updateCadence: "通常 2 次/日，典型完成窗口约 05:30 / 17:30 UTC",
    officialUpdateCadence: "通常 2 次/日，典型完成窗口约 05:30 / 17:30 UTC",
    forecastHorizon: "至 180 小时",
    strengthsZh: ["适合看 provider 自有体系与第三方模型的差异。", "可观察是否偏离主流全球模式。"],
    limitsZh: ["公开技术细节少于国家级机构模型。", "不建议作为唯一权威基准。"],
    officialSourceUrl: "https://content.meteoblue.com/en/research-education/specifications/data-sources/weather-simulation-data/meteoblue-models",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "provider",
    notes: "属于 provider-level source，页面 Last update 比官方运行说明更接近当前展示事实。",
  },
  {
    code: "NEMSGLOBAL_E",
    aliases: ["NEMS2-30"],
    displayName: "NEMS Global E",
    fullName: "meteoblue NEMS Global Ensemble Variant",
    agency: "meteoblue",
    domainType: "全球",
    coverage: "全球",
    resolutionLabel: "约 30 km（provider-level 变体）",
    updateCadence: "通常 2 次/日",
    officialUpdateCadence: "通常 2 次/日",
    forecastHorizon: "至 168 小时",
    strengthsZh: ["适合观察 provider 自有体系中的另一种解。", "对比分歧宽度时有参考价值。"],
    limitsZh: ["公开参数少于机构级模型。", "不适合单独承担可信边界判断。"],
    officialSourceUrl: "https://content.meteoblue.com/en/research-education/specifications/data-sources/weather-simulation-data/meteoblue-models",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "provider",
    notes: "公开资料没有单列该变体，产品中应明确标注为 provider-level 资料。",
  },
  {
    code: "NEMSAS02",
    aliases: ["NEMS-8"],
    displayName: "NEMS Asia 0.2°",
    fullName: "meteoblue NEMS Asia",
    agency: "meteoblue",
    domainType: "区域",
    coverage: "东亚区域",
    resolutionLabel: "约 8 km（provider-level）",
    updateCadence: "通常 2 次/日",
    officialUpdateCadence: "通常 2 次/日",
    forecastHorizon: "至 180 小时",
    strengthsZh: ["东亚区域内温度梯度通常比全球场更细。", "适合观察区域热区和时段偏移。"],
    limitsZh: ["仍不是站点级局地模式。", "公开技术细节有限，需要与其他模式交叉看。"],
    officialSourceUrl: "https://content.meteoblue.com/en/research-education/specifications/data-sources/weather-simulation-data/meteoblue-models",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "provider",
    notes: "资料来自 meteoblue 技术页，适合作为区域补充视角，不等于当前时刻准确率评分。",
  },
  {
    code: "NEMS12",
    aliases: ["NEMS-12"],
    displayName: "NEMS 12 km",
    fullName: "meteoblue NEMS Regional 12 km",
    agency: "meteoblue",
    domainType: "区域",
    coverage: "区域",
    resolutionLabel: "约 12 km（provider-level）",
    updateCadence: "通常 2 次/日",
    officialUpdateCadence: "通常 2 次/日",
    forecastHorizon: "至 180 小时",
    strengthsZh: ["较适合区域尺度温度结构对比。", "可作为全球场与局地场之间的中间参考层。"],
    limitsZh: ["公开细节有限，参数解释以 provider 说明为准。", "不应当作站点实况替代。"],
    officialSourceUrl: "https://content.meteoblue.com/en/research-education/specifications/data-sources/weather-simulation-data/meteoblue-models",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "provider",
    notes: "属于 provider-level 区域模式，适合与 ICON-EU、NAM 等区域模式交叉看。",
  },
  {
    code: "NEMS12_E",
    aliases: ["NEMS2-12", "NEMS-12 E"],
    displayName: "NEMS 12 km E",
    fullName: "meteoblue NEMS Regional 12 km Ensemble Variant",
    agency: "meteoblue",
    domainType: "区域",
    coverage: "区域",
    resolutionLabel: "约 12 km（provider-level 变体）",
    updateCadence: "通常 2 次/日",
    officialUpdateCadence: "通常 2 次/日",
    forecastHorizon: "至 168 小时",
    strengthsZh: ["可用于观察 provider 同分辨率下的解差异。", "有助于识别单模型异常尖峰。"],
    limitsZh: ["公开技术参数较少。", "不适合作为唯一可信边界。"],
    officialSourceUrl: "https://content.meteoblue.com/en/research-education/specifications/data-sources/weather-simulation-data/meteoblue-models",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "provider",
    notes: "产品中应标注为 provider-level 变体资料，避免被误解为官方独立主模式。",
  },
  {
    code: "NEMS4",
    aliases: ["NEMS-4"],
    displayName: "NEMS 4 km",
    fullName: "meteoblue NEMS Regional 4 km",
    agency: "meteoblue",
    domainType: "区域",
    coverage: "区域",
    resolutionLabel: "约 4 km（provider-level）",
    updateCadence: "通常 2 次/日",
    officialUpdateCadence: "通常 2 次/日",
    forecastHorizon: "至 120 小时",
    strengthsZh: ["更细网格下局地温度梯度更直观。", "适合辅助观察机场周边微尺度变化。"],
    limitsZh: ["仍需结合实况与雷达，不可单点定论。", "在复杂地形下可能出现局地误差。"],
    officialSourceUrl: "https://content.meteoblue.com/en/research-education/specifications/data-sources/weather-simulation-data/meteoblue-models",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "provider",
    notes: "用于增强区域细节观察，不代表逐小时绝对准确。",
  },
  {
    code: "NMM22",
    aliases: ["NMM-22", "NMM-12"],
    displayName: "NMM 22 km",
    fullName: "meteoblue NMM Regional 22 km",
    agency: "meteoblue",
    domainType: "区域",
    coverage: "区域",
    resolutionLabel: "约 22 km（provider-level）",
    updateCadence: "通常 2 次/日",
    officialUpdateCadence: "通常 2 次/日",
    forecastHorizon: "至 180 小时",
    strengthsZh: ["与 NEMS 系列互补，便于做区域交叉验证。", "能提供另一套动力核心下的温度演变参考。"],
    limitsZh: ["公开参数说明有限。", "局地降水细节需配合更高分辨率模式。"],
    officialSourceUrl: "https://content.meteoblue.com/en/research-education/specifications/data-sources/weather-simulation-data/meteoblue-models",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "provider",
    notes: "在多模型排序中更适合看相对位置和偏差，不适合单独判定。",
  },
  {
    code: "NMM4",
    aliases: ["NMM-4"],
    displayName: "NMM 4 km",
    fullName: "meteoblue NMM Regional 4 km",
    agency: "meteoblue",
    domainType: "区域",
    coverage: "区域",
    resolutionLabel: "约 4 km（provider-level）",
    updateCadence: "通常 2 次/日",
    officialUpdateCadence: "通常 2 次/日",
    forecastHorizon: "至 120 小时",
    strengthsZh: ["高分辨率下对局地温度场变化更敏感。", "适合和 ICON-D2、HRRR 做短时段对比。"],
    limitsZh: ["公开文档粒度有限。", "极端对流场景下不应脱离雷达和临近实况。"],
    officialSourceUrl: "https://content.meteoblue.com/en/research-education/specifications/data-sources/weather-simulation-data/meteoblue-models",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "provider",
    notes: "用于区域高分辨率补充判断，需与其他模式联合使用。",
  },
  {
    code: "ICONEU",
    aliases: ["ICON-EU", "ICON-7"],
    displayName: "ICON-EU",
    fullName: "DWD ICON-EU",
    agency: "DWD",
    domainType: "区域",
    coverage: "欧洲区域",
    resolutionLabel: "约 6.5-7 km",
    updateCadence: "00/06/12/18 UTC，4 次/日",
    officialUpdateCadence: "00/06/12/18 UTC，4 次/日",
    forecastHorizon: "至 120 小时",
    strengthsZh: ["对欧洲区域温度和风场细节刻画更完整。", "与 ICON 全球场配合可观察尺度下钻后的变化。"],
    limitsZh: ["覆盖范围主要在欧洲。", "超出覆盖边缘时稳定性会下降。"],
    officialSourceUrl: "https://www.dwd.de/EN/ourservices/nwp_forecast_data/nwp_forecast_data.html",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "欧洲地区站点建议优先纳入该模式做区域交叉验证。",
  },
  {
    code: "ICOND2",
    aliases: ["ICON-D2", "ICOND2", "ICOND-2"],
    displayName: "ICON-D2",
    fullName: "DWD ICON-D2",
    agency: "DWD",
    domainType: "区域",
    coverage: "德国及邻近区域",
    resolutionLabel: "约 2.2 km",
    updateCadence: "通常每 3 小时更新",
    officialUpdateCadence: "通常每 3 小时更新",
    forecastHorizon: "至 48 小时",
    strengthsZh: ["对局地温度和边界层变化更敏感。", "适合短时临近参考。"],
    limitsZh: ["覆盖范围有限。", "离开核心覆盖区后可用性下降。"],
    officialSourceUrl: "https://www.dwd.de/EN/ourservices/nwp_forecast_data/nwp_forecast_data.html",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "用于欧洲核心区短时段高分辨率补充，避免外推到远离覆盖区。",
  },
  {
    code: "MFEU",
    aliases: ["ARPEGE-11", "MF-EU"],
    displayName: "Meteo-France Europe",
    fullName: "Meteo-France ARPEGE Europe",
    agency: "Meteo-France",
    domainType: "区域",
    coverage: "欧洲区域",
    resolutionLabel: "约 10-11 km",
    updateCadence: "00/06/12/18 UTC，4 次/日",
    officialUpdateCadence: "00/06/12/18 UTC，4 次/日",
    forecastHorizon: "至 96 小时",
    strengthsZh: ["提供法国体系下的欧洲区域视角。", "和 IFS/ICON-EU 对比时可识别区域偏差。"],
    limitsZh: ["不同 provider 命名可能存在差异。", "局地强对流仍需更高分辨率模式补充。"],
    officialSourceUrl: "https://meteofrance.com/modeles-prevision-meteo",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "展示名称可能由 provider 重命名，解释以官方体系为主。",
  },
  {
    code: "HARMONIE",
    aliases: ["HARMONIE-AROME", "AROME", "HARMN-5"],
    displayName: "HARMONIE",
    fullName: "HARMONIE-AROME Limited Area Model",
    agency: "HIRLAM / ALADIN consortium",
    domainType: "区域",
    coverage: "欧洲部分国家区域",
    resolutionLabel: "约 2-2.5 km（常见配置）",
    updateCadence: "通常每 3-6 小时更新（依业务区而异）",
    officialUpdateCadence: "通常每 3-6 小时更新（依业务区而异）",
    forecastHorizon: "常见 48-60 小时",
    strengthsZh: ["短时局地结构刻画能力较强。", "可与 ICON-D2 / HRRR 类高分辨率模式互证。"],
    limitsZh: ["具体业务区和时效配置差异较大。", "离开业务核心区后稳定性下降。"],
    officialSourceUrl: "https://hirlam.org/index.php/harmonie-system",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "该模式属于业务区依赖较强的区域系统，需结合覆盖范围解释。",
  },
  {
    code: "NAM12",
    aliases: ["NAM-12"],
    displayName: "NAM 12 km",
    fullName: "NOAA NAM 12 km",
    agency: "NOAA / NCEP",
    domainType: "区域",
    coverage: "北美区域",
    resolutionLabel: "约 12 km",
    updateCadence: "00/06/12/18 UTC，4 次/日",
    officialUpdateCadence: "00/06/12/18 UTC，4 次/日",
    forecastHorizon: "至 84 小时",
    strengthsZh: ["北美区域短中时效有稳定参考价值。", "对地形和局地风场有一定表达能力。"],
    limitsZh: ["覆盖范围主要在北美。", "超出区域后不应作为主参考。"],
    officialSourceUrl: "https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/nam.php",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "北美站点建议将其作为区域主力之一，与 GFS/HRRR 联合判断。",
  },
  {
    code: "NAM5",
    aliases: ["NAM-5"],
    displayName: "NAM 5 km",
    fullName: "NOAA NAM Nested 5 km",
    agency: "NOAA / NCEP",
    domainType: "区域",
    coverage: "北美局地嵌套区",
    resolutionLabel: "约 5 km",
    updateCadence: "通常每 6 小时更新",
    officialUpdateCadence: "通常每 6 小时更新",
    forecastHorizon: "常见至 60 小时",
    strengthsZh: ["比 NAM12 提供更细的局地信息。", "对短时温度变化更敏感。"],
    limitsZh: ["覆盖范围与发布策略可能随业务区调整。", "缺测时不应以插值假设补齐。"],
    officialSourceUrl: "https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/nam.php",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "用于北美局地细化判断，建议与 HRRR、实况联合使用。",
  },
  {
    code: "NAM3",
    aliases: ["NAM-3"],
    displayName: "NAM 3 km",
    fullName: "NOAA NAM CONUS Nest 3 km",
    agency: "NOAA / NCEP",
    domainType: "区域",
    coverage: "北美 CONUS 区域",
    resolutionLabel: "约 3 km",
    updateCadence: "通常每 6 小时更新",
    officialUpdateCadence: "通常每 6 小时更新",
    forecastHorizon: "常见至 60 小时",
    strengthsZh: ["局地温度和对流结构更细。", "短临近时效下可补充中尺度模式信息。"],
    limitsZh: ["业务范围集中在北美。", "不能替代临近实况与雷达。"],
    officialSourceUrl: "https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/nam.php",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "更偏向短时临近判断，不宜外推到中长期。",
  },
  {
    code: "HRRR",
    aliases: ["HRRR-3", "HRRR-2"],
    displayName: "HRRR",
    fullName: "NOAA High-Resolution Rapid Refresh",
    agency: "NOAA / NCEP",
    domainType: "区域",
    coverage: "北美 CONUS 区域",
    resolutionLabel: "约 3 km",
    updateCadence: "通常每小时更新",
    officialUpdateCadence: "通常每小时更新",
    forecastHorizon: "常见至 18-48 小时（按发布版本）",
    strengthsZh: ["短时滚动更新频率高，适合临近预报。", "对局地温度和风场变化响应快。"],
    limitsZh: ["时效较短。", "超出覆盖区或长时效场景不宜作为主判断。"],
    officialSourceUrl: "https://rapidrefresh.noaa.gov/hrrr/",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "适合短临近决策，建议结合 NAM/GFS 观察时效衔接。",
  },
  {
    code: "GEM2",
    aliases: ["GEM-2", "RDPS-2"],
    displayName: "GEM 2.5 km",
    fullName: "ECCC High-Resolution GEM Regional",
    agency: "Environment and Climate Change Canada",
    domainType: "区域",
    coverage: "加拿大及邻近区域",
    resolutionLabel: "约 2.5 km",
    updateCadence: "通常每 6-12 小时更新",
    officialUpdateCadence: "通常每 6-12 小时更新",
    forecastHorizon: "常见至 48 小时",
    strengthsZh: ["加拿大区域高分辨率补充价值高。", "与 GEM15 形成区域与全球的层级对照。"],
    limitsZh: ["覆盖范围区域化明显。", "具体发布节奏可能按业务调整。"],
    officialSourceUrl: "https://eccc-msc.github.io/open-data/msc-data/nwp_rdps/readme_rdps-datamart_en/",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "适合北美高纬区域细化判断，注意与全球模式的尺度差异。",
  },
  {
    code: "NBM",
    aliases: ["NBM-Blend", "NBM-2"],
    displayName: "NBM",
    fullName: "NOAA National Blend of Models",
    agency: "NOAA / NWS",
    domainType: "区域",
    coverage: "美国及部分北美区域",
    resolutionLabel: "约 2.5 km（业务产品常见口径）",
    updateCadence: "通常每小时更新",
    officialUpdateCadence: "通常每小时更新",
    forecastHorizon: "常见至 7 天（按要素与版本）",
    strengthsZh: ["融合多模式信息，稳定性通常较好。", "适合做业务层面的综合参考。"],
    limitsZh: ["属于融合产品，不代表单一动力核心。", "局地极端事件仍需查看原始动力模式。"],
    officialSourceUrl: "https://vlab.noaa.gov/web/mdl/nbm",
    verifiedAt,
    officialVerifiedAt: verifiedAt,
    sourceLevel: "official",
    notes: "适合业务汇总视角，建议与主动力模式并读。",
  },
];

export const MODEL_CATALOG = entries;

export const MODEL_CATALOG_MAP: Record<string, ModelCatalogEntry> = Object.fromEntries(
  entries.flatMap((entry) => [[entry.code, entry], [entry.displayName, entry], ...entry.aliases.map((alias) => [alias, entry] as const)]),
);

const normalizeCatalogKey = (value: string) => value.trim().toUpperCase().replace(/[^A-Z0-9]+/g, "");

const MODEL_CATALOG_RESOLVER_MAP = new Map<string, ModelCatalogEntry>();

for (const entry of entries) {
  for (const candidate of [entry.code, entry.displayName, ...entry.aliases]) {
    const normalized = normalizeCatalogKey(candidate);
    if (normalized && !MODEL_CATALOG_RESOLVER_MAP.has(normalized)) {
      MODEL_CATALOG_RESOLVER_MAP.set(normalized, entry);
    }
  }
}

export const resolveModelCatalogEntry = (value: string | null | undefined): ModelCatalogEntry | null => {
  if (!value) {
    return null;
  }

  return MODEL_CATALOG_MAP[value] ?? MODEL_CATALOG_RESOLVER_MAP.get(normalizeCatalogKey(value)) ?? null;
};
