import { describe, expect, test } from "vitest";

import { LOCATION_REGISTRY } from "../src/config.js";
import { buildKellyWorkbench } from "../src/kelly/workbench.js";

describe("buildKellyWorkbench", () => {
  test("builds probability, market pricing, and recommendations from current model signals", () => {
    const location = LOCATION_REGISTRY.miami_mia;

    const result = buildKellyWorkbench({
      location,
      targetDate: "2026-03-28",
      hourly: {
        location: { id: location.id, name: location.name, timezone: location.timezone },
        fetchedAt: "2026-03-28T10:00:00.000Z",
        sourceObservedAt: "2026-03-28T10:00:00.000Z",
        mode: "1h",
        periodHours: 1,
        sourceType: "week-table-1h",
        stale: false,
        pageUrl: location.weekPageUrl,
        parserVersion: "test",
        items: [
          {
            timestamp: "2026-03-28T16:00:00-04:00",
            endAt: null,
            summary: null,
            summaryZh: "下午升温明显",
            iconUrl: null,
            temperatureC: 20,
            feelsLikeC: 20,
            windDirection: null,
            windSpeedKphMin: null,
            windSpeedKphMax: null,
            precipitationMm: null,
            precipitationProbabilityPct: null,
          },
        ],
        fieldCoverage: {
          precipitationProbabilityPct: {
            availableHours: 0,
            totalHours: 1,
            source: "week-table-1h",
            completeness: "missing",
            missingReasons: {
              "source-unpublished": 1,
              "parser-unrecognized": 0,
              "fallback-unavailable": 0,
            },
          },
          feelsLikeC: {
            availableHours: 1,
            totalHours: 1,
            source: "week-table-1h",
            completeness: "full",
            missingReasons: {
              "source-unpublished": 0,
              "parser-unrecognized": 0,
              "fallback-unavailable": 0,
            },
          },
          windDirection: {
            availableHours: 0,
            totalHours: 1,
            source: "week-table-1h",
            completeness: "missing",
            missingReasons: {
              "source-unpublished": 1,
              "parser-unrecognized": 0,
              "fallback-unavailable": 0,
            },
          },
          mixedSources: ["week-table-1h"],
        },
        partial: false,
        warnings: [],
        cacheHit: true,
        current: {
          timestamp: "2026-03-28T16:00:00-04:00",
          temperatureC: 20,
          index: 0,
        },
      },
      report: {
        location: { id: location.id, name: location.name, timezone: location.timezone },
        fetchedAt: "2026-03-28T10:00:00.000Z",
        sourceObservedAt: "2026-03-28T10:00:00.000Z",
        stale: false,
        cacheHit: true,
        pageUrl: location.weekPageUrl,
        parserVersion: "test",
        available: true,
        titleEn: "Weather report",
        sourceTextEn: "Warm afternoon expected.",
        textZh: "下午升温明显，最高温接近 30C。",
        metrics: {
          forecastDayLabel: "Friday",
          maxTemperatureC: 30,
          uvIndex: null,
          overnightWindKphMin: null,
          overnightWindKphMax: null,
          daytimeWindKphMin: null,
          daytimeWindKphMax: null,
          overnightWindDirection: null,
          daytimeWindDirection: null,
          confidence: "high",
          predictability: "high",
          predictabilityScore: 3,
        },
        warnings: [],
      },
      insight: {
        location: { id: location.id, name: location.name, timezone: location.timezone },
        fetchedAt: "2026-03-28T10:00:00.000Z",
        stale: false,
        cacheHit: true,
        pageUrl: location.multimodelPageUrl,
        sourceType: "meteoblue-page-highcharts",
        selectedTimestamp: "2026-03-28T16:00:00-04:00",
        selectedTimestampReason: "requested",
        availableTimestamps: ["2026-03-28T16:00:00-04:00"],
        modelCount: 3,
        modelInventory: [
          { modelName: "IFS", displayName: "IFS", pageOrder: 0, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "IFS", modelCode: "IFS" },
          { modelName: "ECMWF", displayName: "ECMWF", pageOrder: 1, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "ECMWF", modelCode: "ECMWF" },
          { modelName: "GFS", displayName: "GFS", pageOrder: 2, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "GFS", modelCode: "GFS" },
        ],
        referenceTemperature: { temperatureC: 20, source: "assumed-client-value" },
        closestModel: null,
        rankedModels: [
          { modelName: "IFS", currentTemperatureC: 20.2, deltaToActualTemperatureC: 0.2, dayPeakTemperatureC: 30.2, dayPeakTimestamp: "2026-03-28T18:00:00-04:00" },
          { modelName: "ECMWF", currentTemperatureC: 19.7, deltaToActualTemperatureC: -0.3, dayPeakTemperatureC: 29.8, dayPeakTimestamp: "2026-03-28T18:00:00-04:00" },
          { modelName: "GFS", currentTemperatureC: 20.5, deltaToActualTemperatureC: 0.5, dayPeakTemperatureC: 31.1, dayPeakTimestamp: "2026-03-28T19:00:00-04:00" },
        ],
        peakTimeDistribution: [],
        sourceProof: {
          dataFromPage: true,
          usesOfficialApi: false,
          chartFormat: "highcharts",
          pageFetchedAt: "2026-03-28T10:00:00.000Z",
          chartEndpoint: "https://example.com/chart",
          parserVersion: "test",
          modelNames: ["IFS", "ECMWF", "GFS"],
          timestampCount: 1,
          timestampSource: "point-name-local",
          xLabelOffsetMinutes: null,
        },
        warnings: [],
      },
      distribution: {
        location: { id: location.id, name: location.name, timezone: location.timezone },
        fetchedAt: "2026-03-28T10:00:00.000Z",
        stale: false,
        cacheHit: true,
        pageUrl: location.multimodelPageUrl,
        sourceType: "meteoblue-page-highcharts",
        requestedTimestamp: "2026-03-28T16:00:00-04:00",
        selectedTimestamp: "2026-03-28T16:00:00-04:00",
        availableTimestamps: ["2026-03-28T16:00:00-04:00"],
        bucketSizeC: 1,
        modelCount: 3,
        modelInventory: [
          { modelName: "IFS", displayName: "IFS", pageOrder: 0, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "IFS", modelCode: "IFS" },
          { modelName: "ECMWF", displayName: "ECMWF", pageOrder: 1, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "ECMWF", modelCode: "ECMWF" },
          { modelName: "GFS", displayName: "GFS", pageOrder: 2, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "GFS", modelCode: "GFS" },
        ],
        members: [
          { modelName: "IFS", temperatureC: 20.2, peakTemperatureC: 30.2, peakTimestamp: "2026-03-28T18:00:00-04:00" },
          { modelName: "ECMWF", temperatureC: 19.7, peakTemperatureC: 29.8, peakTimestamp: "2026-03-28T18:00:00-04:00" },
          { modelName: "GFS", temperatureC: 20.5, peakTemperatureC: 31.1, peakTimestamp: "2026-03-28T19:00:00-04:00" },
        ],
        distribution: [],
        peakDistribution: [],
        sourceProof: {
          dataFromPage: true,
          usesOfficialApi: false,
          chartFormat: "highcharts",
          pageFetchedAt: "2026-03-28T10:00:00.000Z",
          chartEndpoint: "https://example.com/chart",
          parserVersion: "test",
          modelNames: ["IFS", "ECMWF", "GFS"],
          timestampCount: 1,
          timestampSource: "point-name-local",
          xLabelOffsetMinutes: null,
        },
        highlights: {
          spreadTemperatureC: 1.3,
          dominantBucket: { bucketStartC: 20, bucketEndC: 21, label: "20-21", count: 3, models: ["IFS", "ECMWF", "GFS"] },
          dominantPeakBucket: { bucketStartC: 30, bucketEndC: 31, label: "30-31", count: 2, models: ["IFS", "ECMWF"] },
          coolestMember: { modelName: "ECMWF", temperatureC: 19.7, peakTemperatureC: 29.8, peakTimestamp: "2026-03-28T18:00:00-04:00" },
          warmestMember: { modelName: "GFS", temperatureC: 20.5, peakTemperatureC: 31.1, peakTimestamp: "2026-03-28T19:00:00-04:00" },
          highestPeakMember: { modelName: "GFS", temperatureC: 20.5, peakTemperatureC: 31.1, peakTimestamp: "2026-03-28T19:00:00-04:00" },
        },
        stats: {
          minTemperatureC: 19.7,
          maxTemperatureC: 20.5,
          meanTemperatureC: 20.13,
        },
        warnings: [],
      },
      discoveryCandidates: [
        {
          marketId: "market-yes-30",
          slug: "market-yes-30",
          title: "Will the high temperature in Miami be at least 30C on Mar 28, 2026?",
          marketUrl: "https://example.com/market-yes-30",
          conditionId: "condition-1",
          contractType: "atLeast",
          unit: "C",
          bucketStartC: 30,
          bucketEndC: null,
          bucketLabel: ">= 30.0C",
          parseStatus: "matched",
          exclusionReason: null,
          yesTokenId: "yes-1",
          noTokenId: "no-1",
          updatedAt: "2026-03-28T10:00:00.000Z",
          eventTitle: "Miami weather",
          eventUrl: "https://example.com/event",
          liquidity: 10000,
          volume24h: 5000,
        },
      ],
      discoveryFetchedAt: "2026-03-28T10:00:00.000Z",
      sourceLinks: {
        meteoblueWeekUrl: location.weekPageUrl,
        meteoblueMultimodelUrl: location.multimodelPageUrl,
        polymarketSearchUrl: "https://example.com/search",
        marketUrls: ["https://example.com/market-yes-30"],
      },
      orderBooks: new Map([
        ["yes-1", { tokenId: "yes-1", bestBid: 0.41, bestAsk: 0.42, midpoint: 0.415, updatedAt: "2026-03-28T10:00:01.000Z" }],
        ["no-1", { tokenId: "no-1", bestBid: 0.57, bestAsk: 0.58, midpoint: 0.575, updatedAt: "2026-03-28T10:00:01.000Z" }],
      ]),
      priceFetchedAt: "2026-03-28T10:00:01.000Z",
      options: {
        targetDate: "2026-03-28",
        bankroll: 1000,
        riskMode: "balanced",
        minEdge: 0.02,
        actualTemperatureC: 20,
      },
      warnings: [],
    });

    expect(result.targetDate).toBe("2026-03-28");
    expect(result.probabilityCurve.length).toBeGreaterThan(5);
    expect(result.markets[0]?.fairYes).toBeGreaterThan(0.5);
    expect(result.markets[0]?.recommendedSide).toBe("yes");
    expect(result.recommendations[0]).toMatchObject({
      marketId: "market-yes-30",
      side: "yes",
    });
  });
});

