import { describe, expect, test } from "vitest";

import { LOCATION_REGISTRY } from "../src/config.js";
import { buildKellyWorkbench } from "../src/kelly/workbench.js";

describe("kelly observation fallback regression", () => {
  test("keeps matched contracts visible and returns an observation slot when no contract clears the edge threshold", () => {
    const location = LOCATION_REGISTRY.miami_mia;

    const result = buildKellyWorkbench({
      location,
      targetDate: "2026-03-28",
      hourly: {
        location: { id: location.id, name: location.name, timezone: location.timezone },
        fetchedAt: "2026-03-28T10:00:00.000Z",
        sourceObservedAt: "2026-03-28T10:00:00.000Z",
        mode: "1h",
        periodHours: 1,
        sourceType: "week-table-1h",
        stale: false,
        pageUrl: location.weekPageUrl,
        parserVersion: "test",
        items: [
          {
            timestamp: "2026-03-28T16:00:00-04:00",
            endAt: null,
            summary: "warm",
            summaryZh: null,
            iconUrl: null,
            temperatureC: 30,
            feelsLikeC: 31,
            windDirection: null,
            windSpeedKphMin: null,
            windSpeedKphMax: null,
            precipitationMm: null,
            precipitationProbabilityPct: null,
          },
        ],
        fieldCoverage: {
          precipitationProbabilityPct: {
            availableHours: 0,
            totalHours: 1,
            source: "week-table-1h",
            completeness: "missing",
            missingReasons: {
              "source-unpublished": 1,
              "parser-unrecognized": 0,
              "fallback-unavailable": 0,
            },
          },
          feelsLikeC: {
            availableHours: 1,
            totalHours: 1,
            source: "week-table-1h",
            completeness: "full",
            missingReasons: {
              "source-unpublished": 0,
              "parser-unrecognized": 0,
              "fallback-unavailable": 0,
            },
          },
          windDirection: {
            availableHours: 0,
            totalHours: 1,
            source: "week-table-1h",
            completeness: "missing",
            missingReasons: {
              "source-unpublished": 1,
              "parser-unrecognized": 0,
              "fallback-unavailable": 0,
            },
          },
          mixedSources: ["week-table-1h"],
        },
        partial: false,
        warnings: [],
        cacheHit: true,
        current: {
          timestamp: "2026-03-28T16:00:00-04:00",
          temperatureC: 30,
          index: 0,
        },
      },
      report: {
        location: { id: location.id, name: location.name, timezone: location.timezone },
        fetchedAt: "2026-03-28T10:00:00.000Z",
        sourceObservedAt: "2026-03-28T10:00:00.000Z",
        stale: false,
        cacheHit: true,
        pageUrl: location.weekPageUrl,
        parserVersion: "test",
        available: true,
        titleEn: "Weather report",
        sourceTextEn: "Warm afternoon expected.",
        textZh: null,
        metrics: {
          forecastDayLabel: "Friday",
          maxTemperatureC: 31,
          uvIndex: null,
          overnightWindKphMin: null,
          overnightWindKphMax: null,
          daytimeWindKphMin: null,
          daytimeWindKphMax: null,
          overnightWindDirection: null,
          daytimeWindDirection: null,
          confidence: "high",
          predictability: "high",
          predictabilityScore: 3,
        },
        warnings: [],
      },
      metarObservation: null,
      insight: {
        location: { id: location.id, name: location.name, timezone: location.timezone },
        fetchedAt: "2026-03-28T10:00:00.000Z",
        stale: false,
        cacheHit: true,
        pageUrl: location.multimodelPageUrl,
        sourceType: "meteoblue-page-highcharts",
        selectedTimestamp: "2026-03-28T16:00:00-04:00",
        selectedTimestampReason: "requested",
        availableTimestamps: ["2026-03-28T16:00:00-04:00"],
        modelCount: 3,
        modelInventory: [
          { modelName: "IFS", displayName: "IFS", pageOrder: 0, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "IFS", modelCode: "IFS" },
          { modelName: "ECMWF", displayName: "ECMWF", pageOrder: 1, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "ECMWF", modelCode: "ECMWF" },
          { modelName: "GFS", displayName: "GFS", pageOrder: 2, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "GFS", modelCode: "GFS" },
        ],
        referenceTemperature: { temperatureC: 30, source: "assumed-client-value" },
        closestModel: null,
        rankedModels: [
          { modelName: "IFS", currentTemperatureC: 30.2, deltaToActualTemperatureC: 0.2, dayPeakTemperatureC: 30.6, dayPeakTimestamp: "2026-03-28T18:00:00-04:00" },
          { modelName: "ECMWF", currentTemperatureC: 29.9, deltaToActualTemperatureC: -0.1, dayPeakTemperatureC: 30.4, dayPeakTimestamp: "2026-03-28T18:00:00-04:00" },
          { modelName: "GFS", currentTemperatureC: 30.4, deltaToActualTemperatureC: 0.4, dayPeakTemperatureC: 30.9, dayPeakTimestamp: "2026-03-28T19:00:00-04:00" },
        ],
        peakTimeDistribution: [],
        sourceProof: {
          dataFromPage: true,
          usesOfficialApi: false,
          chartFormat: "highcharts",
          pageFetchedAt: "2026-03-28T10:00:00.000Z",
          chartEndpoint: "https://example.com/chart",
          parserVersion: "test",
          modelNames: ["IFS", "ECMWF", "GFS"],
          timestampCount: 1,
          timestampSource: "point-name-local",
          xLabelOffsetMinutes: null,
        },
        warnings: [],
      },
      distribution: {
        location: { id: location.id, name: location.name, timezone: location.timezone },
        fetchedAt: "2026-03-28T10:00:00.000Z",
        stale: false,
        cacheHit: true,
        pageUrl: location.multimodelPageUrl,
        sourceType: "meteoblue-page-highcharts",
        requestedTimestamp: "2026-03-28T16:00:00-04:00",
        selectedTimestamp: "2026-03-28T16:00:00-04:00",
        availableTimestamps: ["2026-03-28T16:00:00-04:00"],
        bucketSizeC: 1,
        modelCount: 3,
        modelInventory: [
          { modelName: "IFS", displayName: "IFS", pageOrder: 0, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "IFS", modelCode: "IFS" },
          { modelName: "ECMWF", displayName: "ECMWF", pageOrder: 1, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "ECMWF", modelCode: "ECMWF" },
          { modelName: "GFS", displayName: "GFS", pageOrder: 2, pageLastUpdatedAt: null, pageLastUpdatedLabel: null, sourceDisplayName: "GFS", modelCode: "GFS" },
        ],
        members: [
          { modelName: "IFS", temperatureC: 30.2, peakTemperatureC: 30.6, peakTimestamp: "2026-03-28T18:00:00-04:00" },
          { modelName: "ECMWF", temperatureC: 29.9, peakTemperatureC: 30.4, peakTimestamp: "2026-03-28T18:00:00-04:00" },
          { modelName: "GFS", temperatureC: 30.4, peakTemperatureC: 30.9, peakTimestamp: "2026-03-28T19:00:00-04:00" },
        ],
        distribution: [],
        peakDistribution: [],
        sourceProof: {
          dataFromPage: true,
          usesOfficialApi: false,
          chartFormat: "highcharts",
          pageFetchedAt: "2026-03-28T10:00:00.000Z",
          chartEndpoint: "https://example.com/chart",
          parserVersion: "test",
          modelNames: ["IFS", "ECMWF", "GFS"],
          timestampCount: 1,
          timestampSource: "point-name-local",
          xLabelOffsetMinutes: null,
        },
        highlights: {
          spreadTemperatureC: 0.5,
          dominantBucket: { bucketStartC: 30, bucketEndC: 31, label: "30-31", count: 3, models: ["IFS", "ECMWF", "GFS"] },
          dominantPeakBucket: { bucketStartC: 30, bucketEndC: 31, label: "30-31", count: 3, models: ["IFS", "ECMWF", "GFS"] },
          coolestMember: { modelName: "ECMWF", temperatureC: 29.9, peakTemperatureC: 30.4, peakTimestamp: "2026-03-28T18:00:00-04:00" },
          warmestMember: { modelName: "GFS", temperatureC: 30.4, peakTemperatureC: 30.9, peakTimestamp: "2026-03-28T19:00:00-04:00" },
          highestPeakMember: { modelName: "GFS", temperatureC: 30.4, peakTemperatureC: 30.9, peakTimestamp: "2026-03-28T19:00:00-04:00" },
        },
        stats: {
          minTemperatureC: 29.9,
          maxTemperatureC: 30.4,
          meanTemperatureC: 30.16,
        },
        warnings: [],
      },
      discoveryCandidates: [
        {
          marketId: "market-yes-30",
          slug: "market-yes-30",
          title: "Will the high temperature in Miami be at least 30C on Mar 28, 2026?",
          marketUrl: "https://example.com/market-yes-30",
          conditionId: "condition-1",
          contractType: "atLeast",
          unit: "C",
          bucketStartC: 30,
          bucketEndC: null,
          bucketLabel: ">= 30.0C",
          lifecycle: "tradable",
          inactiveReason: null,
          parseStatus: "matched",
          exclusionReason: null,
          yesTokenId: "yes-1",
          noTokenId: "no-1",
          updatedAt: "2026-03-28T10:00:00.000Z",
          eventTitle: "Miami weather",
          eventUrl: "https://example.com/event",
          liquidity: 10000,
          volume24h: 5000,
        },
        {
          marketId: "market-unresolved",
          slug: "market-unresolved",
          title: "Will Miami break the heat record this weekend?",
          marketUrl: "https://example.com/market-unresolved",
          conditionId: "condition-2",
          contractType: "range",
          unit: "C",
          bucketStartC: null,
          bucketEndC: null,
          bucketLabel: "Unparsed",
          lifecycle: "unresolved",
          inactiveReason: null,
          parseStatus: "unresolved",
          exclusionReason: "Market title could not be mapped to a temperature bucket.",
          yesTokenId: null,
          noTokenId: null,
          updatedAt: "2026-03-28T10:00:00.000Z",
          eventTitle: "Miami weather",
          eventUrl: "https://example.com/event",
          liquidity: 3000,
          volume24h: 900,
          description: "Rule summary text",
          resolutionSource: "National Weather Service",
        },
      ],
      discoveryFetchedAt: "2026-03-28T10:00:00.000Z",
      sourceLinks: {
        meteoblueWeekUrl: location.weekPageUrl,
        meteoblueMultimodelUrl: location.multimodelPageUrl,
        polymarketSearchUrl: "https://example.com/search",
        marketUrls: ["https://example.com/market-yes-30"],
      },
      orderBooks: new Map([
        ["yes-1", { tokenId: "yes-1", bestBid: 0.98, bestAsk: 0.99, midpoint: 0.985, updatedAt: "2026-03-28T10:00:01.000Z" }],
        ["no-1", { tokenId: "no-1", bestBid: 0.98, bestAsk: 0.99, midpoint: 0.985, updatedAt: "2026-03-28T10:00:01.000Z" }],
      ]),
      priceFetchedAt: "2026-03-28T10:00:01.000Z",
      generatedAt: "2026-03-28T10:00:02.000Z",
      frameSeries: [],
      options: {
        targetDate: "2026-03-28",
        bankroll: 1000,
        riskMode: "balanced",
        minEdge: 0.02,
        actualTemperatureC: 30,
      },
      warnings: [],
    });

    const matchedMarket = result.markets.find((market) => market.marketId === "market-yes-30");

    expect(result.recommendations).toEqual([]);
    expect(result.bestObservation).toMatchObject({
      marketId: "market-yes-30",
      suggestedStake: 0,
    });
    expect(matchedMarket).toMatchObject({
      marketId: "market-yes-30",
      recommendedSide: "none",
    });
    expect(Math.max(matchedMarket?.edgeYes ?? 0, matchedMarket?.edgeNo ?? 0)).toBeLessThanOrEqual(0.01);
    expect(result.unresolvedMarkets).toHaveLength(1);
    expect(result.unresolvedMarkets[0]?.marketId).toBe("market-unresolved");
    expect(result.marketEvidence).toHaveLength(2);
    expect(result.markets.every((market) => market.parseStatus === "matched")).toBe(true);
    expect(result.markets.some((market) => market.marketId === "market-unresolved")).toBe(false);
  });
});
