export type TimezoneGroup = "asia" | "europe" | "africa" | "americas" | "oceania";
export type DisplayTemperatureUnit = "C" | "F";

const METEOBLUE_BASE_URL = "https://www.meteoblue.com";
const DEFAULT_LOCATION_ID = "shanghai_pvg";

export interface LocationCatalogEntry {
  id: string;
  code: string;
  displayName: string;
  displayNameZh: string;
  shortLabel: string;
  cityName: string;
  countryName: string;
  timezone: string;
  timezoneGroup: TimezoneGroup;
  fallbackDisplayUnit: DisplayTemperatureUnit;
  latitude: number;
  longitude: number;
  aslM: number;
  meteoblueWeekPath: string;
  enabled: boolean;
  sortOrder: number;
}

const LOCATION_CATALOG = {
  shanghai_pvg: {
    id: "shanghai_pvg",
    code: "PVG",
    displayName: "Shanghai Pudong International Airport",
    displayNameZh: "上海浦东国际机场",
    shortLabel: "PVG",
    cityName: "Shanghai",
    countryName: "China",
    timezone: "Asia/Shanghai",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 31.1426792,
    longitude: 121.8052144,
    aslM: 2,
    meteoblueWeekPath: "/en/weather/week/shanghai-pudong-international-airport_china_6301386",
    enabled: true,
    sortOrder: 10,
  },
  wuhan_wuh: {
    id: "wuhan_wuh",
    code: "WUH",
    displayName: "Wuhan Tianhe International Airport",
    displayNameZh: "武汉天河国际机场",
    shortLabel: "WUH",
    cityName: "Wuhan",
    countryName: "China",
    timezone: "Asia/Shanghai",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 30.776598,
    longitude: 114.2137146,
    aslM: 34,
    meteoblueWeekPath: "/en/weather/week/wuhan-tianhe-international-airport_china_6301368",
    enabled: true,
    sortOrder: 20,
  },
  istanbul_ist: {
    id: "istanbul_ist",
    code: "IST",
    displayName: "Istanbul Airport",
    displayNameZh: "伊斯坦布尔机场",
    shortLabel: "IST",
    cityName: "Istanbul",
    countryName: "Republic of Turkiye",
    timezone: "Europe/Istanbul",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 41.2657398,
    longitude: 28.7420522,
    aslM: 99,
    meteoblueWeekPath: "/en/weather/week/istanbul-airport_republic-of-t%C3%BCrkiye_11838481",
    enabled: true,
    sortOrder: 10,
  },
  munich_muc: {
    id: "munich_muc",
    code: "MUC",
    displayName: "Munich Airport Franz Josef Strauss International Airport",
    displayNameZh: "慕尼黑机场",
    shortLabel: "MUC",
    cityName: "Munich",
    countryName: "Germany",
    timezone: "Europe/Berlin",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 48.3536623,
    longitude: 11.7750277,
    aslM: 449,
    meteoblueWeekPath:
      "/en/weather/week/munich-airport-franz-josef-strauss-international-airport_germany_3208399",
    enabled: true,
    sortOrder: 20,
  },
  toronto_yyz: {
    id: "toronto_yyz",
    code: "YYZ",
    displayName: "Toronto Pearson International Airport",
    displayNameZh: "多伦多皮尔逊国际机场",
    shortLabel: "YYZ",
    cityName: "Toronto",
    countryName: "Canada",
    timezone: "America/Toronto",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "C",
    latitude: 43.6776612,
    longitude: -79.6248197,
    aslM: 173,
    meteoblueWeekPath: "/en/weather/week/toronto-pearson-international-airport_canada_6296338",
    enabled: true,
    sortOrder: 10,
  },
  miami_mia: {
    id: "miami_mia",
    code: "MIA",
    displayName: "Miami International Airport",
    displayNameZh: "迈阿密国际机场",
    shortLabel: "MIA",
    cityName: "Miami",
    countryName: "United States",
    timezone: "America/New_York",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 25.7934494,
    longitude: -80.2905556,
    aslM: 2,
    meteoblueWeekPath: "/en/weather/week/miami-international-airport_united-states_4164181",
    enabled: true,
    sortOrder: 20,
  },
  losangeles_lax: {
    id: "losangeles_lax",
    code: "LAX",
    displayName: "Los Angeles International Airport",
    displayNameZh: "洛杉矶国际机场",
    shortLabel: "LAX",
    cityName: "Los Angeles",
    countryName: "United States",
    timezone: "America/Los_Angeles",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 33.9415889,
    longitude: -118.40853,
    aslM: 38,
    meteoblueWeekPath: "/en/weather/week/los-angeles-international-airport_united-states_5391958",
    enabled: true,
    sortOrder: 30,
  },
  amsterdam_ams: {
    id: "amsterdam_ams",
    code: "AMS",
    displayName: "Amsterdam Airport Schiphol",
    displayNameZh: "阿姆斯特丹史基浦机场",
    shortLabel: "AMS",
    cityName: "Amsterdam",
    countryName: "The Netherlands",
    timezone: "Europe/Amsterdam",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 52.3103,
    longitude: 4.76028,
    aslM: -3,
    meteoblueWeekPath: "/en/weather/week/amsterdam-airport-schiphol_the-netherlands_6296680",
    enabled: true,
    sortOrder: 30,
  },
  ankara_esb: {
    id: "ankara_esb",
    code: "ESB",
    displayName: "Ankara Esenboga International Airport",
    displayNameZh: "安卡拉埃森博阿国际机场",
    shortLabel: "ESB",
    cityName: "Ankara",
    countryName: "Republic of Turkiye",
    timezone: "Europe/Istanbul",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 40.1281,
    longitude: 32.9951,
    aslM: 952,
    meteoblueWeekPath: "/en/weather/week/ankara-esenbo%c4%9fa-international-airport_republic-of-t%c3%bcrkiye_6299725",
    enabled: true,
    sortOrder: 40,
  },
  atlanta_atl: {
    id: "atlanta_atl",
    code: "ATL",
    displayName: "Hartsfield-Jackson Atlanta International Airport",
    displayNameZh: "亚特兰大哈茨菲尔德-杰克逊国际机场",
    shortLabel: "ATL",
    cityName: "Atlanta",
    countryName: "United States",
    timezone: "America/New_York",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 33.641,
    longitude: -84.4227,
    aslM: 304,
    meteoblueWeekPath: "/en/weather/week/hartsfield-jackson-atlanta-international-airport_united-states_4199556",
    enabled: true,
    sortOrder: 30,
  },
  austin_aus: {
    id: "austin_aus",
    code: "AUS",
    displayName: "Austin-Bergstrom International Airport",
    displayNameZh: "奥斯汀伯格斯特龙国际机场",
    shortLabel: "AUS",
    cityName: "Austin",
    countryName: "United States",
    timezone: "America/Chicago",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 30.1945,
    longitude: -97.6699,
    aslM: 150,
    meteoblueWeekPath: "/en/weather/week/austin-bergstrom-international-airport_united-states_4673601",
    enabled: true,
    sortOrder: 40,
  },
  beijing_pek: {
    id: "beijing_pek",
    code: "PEK",
    displayName: "Beijing Capital International Airport",
    displayNameZh: "北京首都国际机场",
    shortLabel: "PEK",
    cityName: "Beijing",
    countryName: "China",
    timezone: "Asia/Shanghai",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 40.0801,
    longitude: 116.585,
    aslM: 35,
    meteoblueWeekPath: "/en/weather/week/beijing-capital-international-airport_china_6301354",
    enabled: true,
    sortOrder: 30,
  },
  guangzhou_can: {
    id: "guangzhou_can",
    code: "CAN",
    displayName: "Guangzhou Baiyun International Airport",
    displayNameZh: "广州白云国际机场",
    shortLabel: "CAN",
    cityName: "Guangzhou",
    countryName: "China",
    timezone: "Asia/Shanghai",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 23.3924,
    longitude: 113.2988,
    aslM: 15,
    meteoblueWeekPath: "/en/weather/week/guangzhou-baiyun-international-airport_china_6301359",
    enabled: true,
    sortOrder: 35,
  },
  buenosaires_eze: {
    id: "buenosaires_eze",
    code: "EZE",
    displayName: "Ministro Pistarini International Airport",
    displayNameZh: "布宜诺斯艾利斯埃塞萨国际机场",
    shortLabel: "EZE",
    cityName: "Buenos Aires",
    countryName: "Argentina",
    timezone: "America/Argentina/Buenos_Aires",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "C",
    latitude: -34.8222,
    longitude: -58.5358,
    aslM: 20,
    meteoblueWeekPath: "/en/weather/week/ministro-pistarini-international-airport_argentina_6300524",
    enabled: true,
    sortOrder: 50,
  },
  busan_pus: {
    id: "busan_pus",
    code: "PUS",
    displayName: "Busan Gimhae International Airport",
    displayNameZh: "釜山金海国际机场",
    shortLabel: "PUS",
    cityName: "Busan",
    countryName: "South Korea",
    timezone: "Asia/Seoul",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 35.1795,
    longitude: 128.938,
    aslM: 1,
    meteoblueWeekPath: "/en/weather/week/busan-%2f-gimhae-international-airport_south-korea_6300424",
    enabled: true,
    sortOrder: 40,
  },
  capetown_cpt: {
    id: "capetown_cpt",
    code: "CPT",
    displayName: "Cape Town International Airport",
    displayNameZh: "开普敦国际机场",
    shortLabel: "CPT",
    cityName: "Cape Town",
    countryName: "South Africa",
    timezone: "Africa/Johannesburg",
    timezoneGroup: "africa",
    fallbackDisplayUnit: "C",
    latitude: -33.9648,
    longitude: 18.6017,
    aslM: 46,
    meteoblueWeekPath: "/en/weather/week/cape-town-international-airport_south-africa_3368972",
    enabled: true,
    sortOrder: 10,
  },
  chengdu_ctu: {
    id: "chengdu_ctu",
    code: "CTU",
    displayName: "Chengdu Shuangliu International Airport",
    displayNameZh: "成都双流国际机场",
    shortLabel: "CTU",
    cityName: "Chengdu",
    countryName: "China",
    timezone: "Asia/Shanghai",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 30.5785,
    longitude: 103.947,
    aslM: 495,
    meteoblueWeekPath: "/en/weather/week/chengdu-shuangliu-international-airport_china_6301392",
    enabled: true,
    sortOrder: 50,
  },
  chicago_ord: {
    id: "chicago_ord",
    code: "ORD",
    displayName: "Chicago O'Hare International Airport",
    displayNameZh: "芝加哥奥黑尔国际机场",
    shortLabel: "ORD",
    cityName: "Chicago",
    countryName: "United States",
    timezone: "America/Chicago",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 41.9796,
    longitude: -87.9045,
    aslM: 201,
    meteoblueWeekPath: "/en/weather/week/chicago-o%27hare-international-airport_united-states_4887479",
    enabled: true,
    sortOrder: 60,
  },
  chongqing_ckg: {
    id: "chongqing_ckg",
    code: "CKG",
    displayName: "Chongqing Jiangbei International Airport",
    displayNameZh: "重庆江北国际机场",
    shortLabel: "CKG",
    cityName: "Chongqing",
    countryName: "China",
    timezone: "Asia/Shanghai",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 29.7192,
    longitude: 106.642,
    aslM: 416,
    meteoblueWeekPath: "/en/weather/week/chongqing-jiangbei-international-airport_china_6301390",
    enabled: true,
    sortOrder: 60,
  },
  dallas_dal: {
    id: "dallas_dal",
    code: "DAL",
    displayName: "Dallas Love Field",
    displayNameZh: "达拉斯爱田机场",
    shortLabel: "DAL",
    cityName: "Dallas",
    countryName: "United States",
    timezone: "America/Chicago",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 32.8471,
    longitude: -96.852,
    aslM: 145,
    meteoblueWeekPath: "/en/weather/week/dallas-love-field_united-states_4684922",
    enabled: true,
    sortOrder: 70,
  },
  denver_bfk: {
    id: "denver_bfk",
    code: "BFK",
    displayName: "Buckley Air Force Base",
    displayNameZh: "丹佛巴克利空军基地",
    shortLabel: "BFK",
    cityName: "Denver",
    countryName: "United States",
    timezone: "America/Denver",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 39.7056,
    longitude: -104.755,
    aslM: 1706,
    meteoblueWeekPath: "/en/weather/week/buckley-air-force-base_united-states_5415293",
    enabled: true,
    sortOrder: 80,
  },
  helsinki_hel: {
    id: "helsinki_hel",
    code: "HEL",
    displayName: "Helsinki Airport",
    displayNameZh: "赫尔辛基机场",
    shortLabel: "HEL",
    cityName: "Helsinki",
    countryName: "Finland",
    timezone: "Europe/Helsinki",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 60.3172,
    longitude: 24.9633,
    aslM: 54,
    meteoblueWeekPath: "/en/weather/week/helsinki-airport_finland_6301511",
    enabled: true,
    sortOrder: 50,
  },
  hongkong_hkg: {
    id: "hongkong_hkg",
    code: "HKG",
    displayName: "Chek Lap Kok Airport",
    displayNameZh: "香港赤鱲角机场",
    shortLabel: "HKG",
    cityName: "Hong Kong",
    countryName: "Hong Kong",
    timezone: "Asia/Hong_Kong",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 22.3155,
    longitude: 113.934,
    aslM: 8,
    meteoblueWeekPath: "/en/weather/week/chek-lap-kok-airport_hong-kong_6301089",
    enabled: true,
    sortOrder: 70,
  },
  laufau_shan_lfs: {
    id: "laufau_shan_lfs",
    code: "LFS",
    displayName: "Lau Fau Shan",
    displayNameZh: "香港流浮山",
    shortLabel: "LFS",
    cityName: "Lau Fau Shan",
    countryName: "Hong Kong",
    timezone: "Asia/Hong_Kong",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 22.4686,
    longitude: 113.997,
    aslM: 10,
    meteoblueWeekPath: "/en/weather/week/lau-fau-shan_hong-kong_1819535",
    enabled: true,
    sortOrder: 75,
  },
  houston_hou: {
    id: "houston_hou",
    code: "HOU",
    displayName: "Houston Hobby Airport",
    displayNameZh: "休斯敦霍比机场",
    shortLabel: "HOU",
    cityName: "Houston",
    countryName: "United States",
    timezone: "America/Chicago",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 29.6524,
    longitude: -95.2772,
    aslM: 13,
    meteoblueWeekPath: "/en/weather/week/houston-hobby_united-states_4741989",
    enabled: true,
    sortOrder: 90,
  },
  jakarta_hlp: {
    id: "jakarta_hlp",
    code: "HLP",
    displayName: "Halim Perdanakusuma Airport",
    displayNameZh: "雅加达哈利姆机场",
    shortLabel: "HLP",
    cityName: "Jakarta",
    countryName: "Indonesia",
    timezone: "Asia/Jakarta",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: -6.26612,
    longitude: 106.892,
    aslM: 30,
    meteoblueWeekPath: "/en/weather/week/halim-perdanakusuma-airport_indonesia_6301224",
    enabled: true,
    sortOrder: 80,
  },
  jeddah_jed: {
    id: "jeddah_jed",
    code: "JED",
    displayName: "Jeddah King Abdul Aziz International Airport",
    displayNameZh: "吉达阿卜杜勒阿齐兹国王国际机场",
    shortLabel: "JED",
    cityName: "Jeddah",
    countryName: "Saudi Arabia",
    timezone: "Asia/Riyadh",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 21.6698,
    longitude: 39.1505,
    aslM: 14,
    meteoblueWeekPath: "/en/weather/week/jeddah-king-abdul-aziz-international-airport_saudi-arabia_6300018",
    enabled: true,
    sortOrder: 90,
  },
  kualalumpur_kul: {
    id: "kualalumpur_kul",
    code: "KUL",
    displayName: "Kuala Lumpur International Airport",
    displayNameZh: "吉隆坡国际机场",
    shortLabel: "KUL",
    cityName: "Kuala Lumpur",
    countryName: "Malaysia",
    timezone: "Asia/Kuala_Lumpur",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 2.74558,
    longitude: 101.71,
    aslM: 21,
    meteoblueWeekPath: "/en/weather/week/kuala-lumpur-international-airport_malaysia_6301255",
    enabled: true,
    sortOrder: 100,
  },
  karachi_khi: {
    id: "karachi_khi",
    code: "KHI",
    displayName: "Jinnah International Airport",
    displayNameZh: "卡拉奇真纳国际机场",
    shortLabel: "KHI",
    cityName: "Karachi",
    countryName: "Pakistan",
    timezone: "Asia/Karachi",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 24.9065,
    longitude: 67.1608,
    aslM: 30,
    meteoblueWeekPath: "/en/weather/week/karachi-airport_pakistan_6300111",
    enabled: true,
    sortOrder: 95,
  },
  lagos_los: {
    id: "lagos_los",
    code: "LOS",
    displayName: "Murtala Mohammed International Airport",
    displayNameZh: "拉各斯穆尔塔拉穆罕默德国际机场",
    shortLabel: "LOS",
    cityName: "Lagos",
    countryName: "Nigeria",
    timezone: "Africa/Lagos",
    timezoneGroup: "africa",
    fallbackDisplayUnit: "C",
    latitude: 6.57737,
    longitude: 3.32116,
    aslM: 41,
    meteoblueWeekPath: "/en/weather/week/murtala-mohammed-international-airport_nigeria_2332458",
    enabled: true,
    sortOrder: 20,
  },
  london_lcy: {
    id: "london_lcy",
    code: "LCY",
    displayName: "London City Airport",
    displayNameZh: "伦敦城市机场",
    shortLabel: "LCY",
    cityName: "London",
    countryName: "United Kingdom",
    timezone: "Europe/London",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 51.5053,
    longitude: 0.05528,
    aslM: 5,
    meteoblueWeekPath: "/en/weather/week/london-city-airport_united-kingdom_6296599",
    enabled: true,
    sortOrder: 60,
  },
  lucknow_lko: {
    id: "lucknow_lko",
    code: "LKO",
    displayName: "Chaudhary Charan Singh Airport",
    displayNameZh: "勒克瑙乔杜里查兰辛格机场",
    shortLabel: "LKO",
    cityName: "Lucknow",
    countryName: "India",
    timezone: "Asia/Kolkata",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 26.7606,
    longitude: 80.8893,
    aslM: 124,
    meteoblueWeekPath: "/en/weather/week/chaudhary-charan-singh-airport_india_6301873",
    enabled: true,
    sortOrder: 110,
  },
  manila_mnl: {
    id: "manila_mnl",
    code: "MNL",
    displayName: "Ninoy Aquino International Airport",
    displayNameZh: "马尼拉尼诺伊阿基诺国际机场",
    shortLabel: "MNL",
    cityName: "Manila",
    countryName: "Philippines",
    timezone: "Asia/Manila",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 14.5086,
    longitude: 121.0198,
    aslM: 23,
    meteoblueWeekPath: "/en/weather/week/ninoy-aquino-international-airport_philippines_1701661",
    enabled: true,
    sortOrder: 115,
  },
  masroor_opmr: {
    id: "masroor_opmr",
    code: "OPMR",
    displayName: "Masroor Air Base",
    displayNameZh: "马斯鲁尔空军基地",
    shortLabel: "OPMR",
    cityName: "Karachi",
    countryName: "Pakistan",
    timezone: "Asia/Karachi",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 24.8936,
    longitude: 66.9388,
    aslM: 15,
    meteoblueWeekPath: "/en/weather/week/masroor_pakistan_7046722",
    enabled: true,
    sortOrder: 96,
  },
  madrid_mad: {
    id: "madrid_mad",
    code: "MAD",
    displayName: "Adolfo Suarez Madrid-Barajas Airport",
    displayNameZh: "马德里巴拉哈斯机场",
    shortLabel: "MAD",
    cityName: "Madrid",
    countryName: "Spain",
    timezone: "Europe/Madrid",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 40.4918,
    longitude: -3.56948,
    aslM: 609,
    meteoblueWeekPath: "/en/weather/week/adolfo-su%c3%a1rez-madrid%e2%80%93barajas-airport_spain_6299345",
    enabled: true,
    sortOrder: 70,
  },
  mexicocity_mex: {
    id: "mexicocity_mex",
    code: "MEX",
    displayName: "Benito Juarez International Airport",
    displayNameZh: "墨西哥城贝尼托华雷斯国际机场",
    shortLabel: "MEX",
    cityName: "Mexico City",
    countryName: "Mexico",
    timezone: "America/Mexico_City",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "C",
    latitude: 19.4363,
    longitude: -99.0721,
    aslM: 2229,
    meteoblueWeekPath: "/en/weather/week/benito-ju%c3%a1rez-international-airport_mexico_6299859",
    enabled: true,
    sortOrder: 100,
  },
  milan_mxp: {
    id: "milan_mxp",
    code: "MXP",
    displayName: "Milano Malpensa Airport",
    displayNameZh: "米兰马尔彭萨机场",
    shortLabel: "MXP",
    cityName: "Milan",
    countryName: "Italy",
    timezone: "Europe/Rome",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 45.6275,
    longitude: 8.71508,
    aslM: 233,
    meteoblueWeekPath: "/en/weather/week/milano-malpensa-airport_italy_3174133",
    enabled: true,
    sortOrder: 80,
  },
  moscow_vko: {
    id: "moscow_vko",
    code: "VKO",
    displayName: "Vnukovo International Airport",
    displayNameZh: "莫斯科伏努科沃国际机场",
    shortLabel: "VKO",
    cityName: "Moscow",
    countryName: "Russia",
    timezone: "Europe/Moscow",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 55.5915,
    longitude: 37.2615,
    aslM: 208,
    meteoblueWeekPath: "/en/weather/week/vnukovo-international-airport_russia_6301018",
    enabled: true,
    sortOrder: 90,
  },
  newyork_lga: {
    id: "newyork_lga",
    code: "LGA",
    displayName: "LaGuardia Airport",
    displayNameZh: "纽约拉瓜迪亚机场",
    shortLabel: "LGA",
    cityName: "New York",
    countryName: "United States",
    timezone: "America/New_York",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 40.7761,
    longitude: -73.8727,
    aslM: 2,
    meteoblueWeekPath: "/en/weather/week/laguardia-airport_united-states_5123698",
    enabled: true,
    sortOrder: 110,
  },
  panamacity_pac: {
    id: "panamacity_pac",
    code: "PAC",
    displayName: "Albrook Marcos A. Gelabert International Airport",
    displayNameZh: "巴拿马城阿尔布鲁克机场",
    shortLabel: "PAC",
    cityName: "Panama City",
    countryName: "Panama",
    timezone: "America/Panama",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "C",
    latitude: 8.97334,
    longitude: -79.5556,
    aslM: 9,
    meteoblueWeekPath: "/en/weather/week/albrook-marcos-a.-gelabert-international-airport_panama_3704579",
    enabled: true,
    sortOrder: 120,
  },
  paris_cdg: {
    id: "paris_cdg",
    code: "CDG",
    displayName: "Paris Charles de Gaulle Airport",
    displayNameZh: "巴黎戴高乐机场",
    shortLabel: "CDG",
    cityName: "Paris",
    countryName: "France",
    timezone: "Europe/Paris",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 49.0128,
    longitude: 2.55,
    aslM: 119,
    meteoblueWeekPath: "/en/weather/week/paris-charles-de-gaulle-airport_france_6269554",
    enabled: true,
    sortOrder: 100,
  },
  sanfrancisco_sfo: {
    id: "sanfrancisco_sfo",
    code: "SFO",
    displayName: "San Francisco International Airport",
    displayNameZh: "旧金山国际机场",
    shortLabel: "SFO",
    cityName: "San Francisco",
    countryName: "United States",
    timezone: "America/Los_Angeles",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 37.6188,
    longitude: -122.376,
    aslM: 5,
    meteoblueWeekPath: "/en/weather/week/san-francisco-international-airport_united-states_5391989",
    enabled: true,
    sortOrder: 130,
  },
  saopaulo_gru: {
    id: "saopaulo_gru",
    code: "GRU",
    displayName: "Sao Paulo-Guarulhos International Airport",
    displayNameZh: "圣保罗瓜鲁柳斯国际机场",
    shortLabel: "GRU",
    cityName: "Sao Paulo",
    countryName: "Brazil",
    timezone: "America/Sao_Paulo",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "C",
    latitude: -23.4306,
    longitude: -46.481,
    aslM: 749,
    meteoblueWeekPath: "/en/weather/week/s%c3%a3o-paulo%e2%80%93guarulhos-international-airport_brazil_6300629",
    enabled: true,
    sortOrder: 140,
  },
  seattle_sea: {
    id: "seattle_sea",
    code: "SEA",
    displayName: "Seattle-Tacoma International Airport",
    displayNameZh: "西雅图塔科马国际机场",
    shortLabel: "SEA",
    cityName: "Seattle",
    countryName: "United States",
    timezone: "America/Los_Angeles",
    timezoneGroup: "americas",
    fallbackDisplayUnit: "F",
    latitude: 47.449,
    longitude: -122.309,
    aslM: 120,
    meteoblueWeekPath: "/en/weather/week/seattle-tacoma-international-airport_united-states_5809876",
    enabled: true,
    sortOrder: 150,
  },
  seoul_icn: {
    id: "seoul_icn",
    code: "ICN",
    displayName: "Incheon International Airport",
    displayNameZh: "仁川国际机场",
    shortLabel: "ICN",
    cityName: "Seoul",
    countryName: "South Korea",
    timezone: "Asia/Seoul",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 37.4492,
    longitude: 126.451,
    aslM: 7,
    meteoblueWeekPath: "/en/weather/week/incheon-international-airport_south-korea_6300433",
    enabled: true,
    sortOrder: 120,
  },
  shenzhen_szx: {
    id: "shenzhen_szx",
    code: "SZX",
    displayName: "Shenzhen Bao'an International Airport",
    displayNameZh: "深圳宝安国际机场",
    shortLabel: "SZX",
    cityName: "Shenzhen",
    countryName: "China",
    timezone: "Asia/Shanghai",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 22.6393,
    longitude: 113.811,
    aslM: 3,
    meteoblueWeekPath: "/en/weather/week/shenzhen-bao%27an-international-airport_china_6301365",
    enabled: true,
    sortOrder: 130,
  },
  singapore_sin: {
    id: "singapore_sin",
    code: "SIN",
    displayName: "Singapore Changi Airport",
    displayNameZh: "新加坡樟宜机场",
    shortLabel: "SIN",
    cityName: "Singapore",
    countryName: "Singapore",
    timezone: "Asia/Singapore",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 1.35514,
    longitude: 103.99,
    aslM: 6,
    meteoblueWeekPath: "/en/weather/week/singapore-changi-airport_singapore_1880725",
    enabled: true,
    sortOrder: 140,
  },
  taipei_tpe: {
    id: "taipei_tpe",
    code: "TPE",
    displayName: "Taiwan Taoyuan International Airport",
    displayNameZh: "台湾桃园国际机场",
    shortLabel: "TPE",
    cityName: "Taipei",
    countryName: "Taiwan",
    timezone: "Asia/Taipei",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 25.0777,
    longitude: 121.233,
    aslM: 32,
    meteoblueWeekPath: "/en/weather/week/taiwan-taoyuan-international-airport_taiwan_1980018",
    enabled: true,
    sortOrder: 150,
  },
  telaviv_tlv: {
    id: "telaviv_tlv",
    code: "TLV",
    displayName: "Ben Gurion Airport",
    displayNameZh: "特拉维夫本古里安机场",
    shortLabel: "TLV",
    cityName: "Tel Aviv",
    countryName: "Israel",
    timezone: "Asia/Jerusalem",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 32.0136,
    longitude: 34.8866,
    aslM: 35,
    meteoblueWeekPath: "/en/weather/week/ben-gurion-airport_israel_390285",
    enabled: true,
    sortOrder: 160,
  },
  tokyo_hnd: {
    id: "tokyo_hnd",
    code: "HND",
    displayName: "Tokyo International Airport",
    displayNameZh: "东京羽田机场",
    shortLabel: "HND",
    cityName: "Tokyo",
    countryName: "Japan",
    timezone: "Asia/Tokyo",
    timezoneGroup: "asia",
    fallbackDisplayUnit: "C",
    latitude: 35.5523,
    longitude: 139.78,
    aslM: 10,
    meteoblueWeekPath: "/en/weather/week/tokyo-international-airport_japan_6300412",
    enabled: true,
    sortOrder: 170,
  },
  warsaw_waw: {
    id: "warsaw_waw",
    code: "WAW",
    displayName: "Warsaw Chopin Airport",
    displayNameZh: "华沙肖邦机场",
    shortLabel: "WAW",
    cityName: "Warsaw",
    countryName: "Poland",
    timezone: "Europe/Warsaw",
    timezoneGroup: "europe",
    fallbackDisplayUnit: "C",
    latitude: 52.1657,
    longitude: 20.9671,
    aslM: 110,
    meteoblueWeekPath: "/en/weather/week/warsaw-chopin-airport_poland_6296786",
    enabled: true,
    sortOrder: 110,
  },
  wellington_wlg: {
    id: "wellington_wlg",
    code: "WLG",
    displayName: "Wellington International Airport",
    displayNameZh: "惠灵顿国际机场",
    shortLabel: "WLG",
    cityName: "Wellington",
    countryName: "New Zealand",
    timezone: "Pacific/Auckland",
    timezoneGroup: "oceania",
    fallbackDisplayUnit: "C",
    latitude: -41.3272,
    longitude: 174.805,
    aslM: 12,
    meteoblueWeekPath: "/en/weather/week/wellington-international-airport_new-zealand_6244688",
    enabled: true,
    sortOrder: 10,
  },
} as const satisfies Record<string, LocationCatalogEntry>;

export type LocationId = keyof typeof LOCATION_CATALOG;
export const TIMEZONE_GROUP_ORDER: TimezoneGroup[] = ["asia", "europe", "africa", "americas", "oceania"];
export const DEFAULT_LOCATION: LocationId = DEFAULT_LOCATION_ID as LocationId;

export interface RegisteredLocation extends Omit<LocationCatalogEntry, "id"> {
  id: LocationId;
  name: string;
  weekPageUrl: string;
  multimodelPageUrl: string;
}

export const buildWeekPageUrl = (entry: LocationCatalogEntry) => `${METEOBLUE_BASE_URL}${entry.meteoblueWeekPath}`;

export const buildMultimodelPageUrl = (entry: LocationCatalogEntry) =>
  `${METEOBLUE_BASE_URL}${entry.meteoblueWeekPath.replace("/weather/week/", "/weather/forecast/multimodel/")}`;

const toRegisteredLocation = <T extends LocationCatalogEntry>(entry: T): RegisteredLocation => ({
  ...entry,
  id: entry.id as LocationId,
  name: entry.displayName,
  weekPageUrl: buildWeekPageUrl(entry),
  multimodelPageUrl: buildMultimodelPageUrl(entry),
});

export const LOCATION_REGISTRY: Record<LocationId, RegisteredLocation> = Object.fromEntries(
  Object.values(LOCATION_CATALOG).map((entry) => [entry.id, toRegisteredLocation(entry)]),
) as Record<LocationId, RegisteredLocation>;

export const getLocationFallbackDisplayUnit = (locationId: LocationId): DisplayTemperatureUnit =>
  LOCATION_REGISTRY[locationId].fallbackDisplayUnit;

export const LOCATION_DIRECTORY: RegisteredLocation[] = Object.values(LOCATION_REGISTRY)
  .filter((entry) => entry.enabled)
  .sort(
    (left, right) =>
      TIMEZONE_GROUP_ORDER.indexOf(left.timezoneGroup) - TIMEZONE_GROUP_ORDER.indexOf(right.timezoneGroup) ||
      left.sortOrder - right.sortOrder ||
      left.displayName.localeCompare(right.displayName),
  );

const readNumber = (key: string, fallback: number): number => {
  const raw = process.env[key];
  if (!raw) {
    return fallback;
  }

  const value = Number.parseInt(raw, 10);
  return Number.isFinite(value) ? value : fallback;
};

export const config = {
  port: readNumber("PORT", 3000),
  host: process.env.HOST ?? "0.0.0.0",
  weekPageTtlMs: readNumber("WEEK_PAGE_TTL_MS", 90_000),
  multimodelImageTtlMs: readNumber("MULTIMODEL_IMAGE_TTL_MS", 300_000),
  multimodelDistributionTtlMs: readNumber("MULTIMODEL_STATS_TTL_MS", 120_000),
  polymarketMarketTtlMs: readNumber("POLYMARKET_MARKET_TTL_MS", 60_000),
  polymarketOrderbookTtlMs: readNumber("POLYMARKET_ORDERBOOK_TTL_MS", 5_000),
  httpTimeoutMs: readNumber("HTTP_TIMEOUT_MS", 30_000),
  tafProvider: process.env.TAF_PROVIDER ?? "auto",
  avwxApiKey: process.env.AVWX_API_KEY ?? "",
  avwxBaseUrl: process.env.AVWX_BASE_URL ?? "https://avwx.rest/api",
  checkwxApiKey: process.env.CHECKWX_API_KEY ?? "",
  checkwxBaseUrl: process.env.CHECKWX_BASE_URL ?? "https://api.checkwx.com",
  polymarketGammaBaseUrl: process.env.POLYMARKET_GAMMA_BASE_URL ?? "https://gamma-api.polymarket.com",
  polymarketClobBaseUrl: process.env.POLYMARKET_CLOB_BASE_URL ?? "https://clob.polymarket.com",
  polymarketClobWsUrl:
    process.env.POLYMARKET_CLOB_WS_URL ?? "wss://ws-subscriptions-clob.polymarket.com/ws/market",
  userAgent:
    process.env.USER_AGENT ??
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) weather-relay/0.2",
};
